### ISSUE TITLE
The link shortner service is currently throwing HTTP 525 errors

### ISSUE THREAD

**Issue by kdenhartog** [zcash/protocol.z.cash#1]
e.g. going to https://p.z.cash/orchard-0.1:commit-ivk-decompositions or any of the other https://p.z.cash links in the orchard lib comments throws a HTTP 525 error from Cloudflare. This is being seen in both Brave and Firefox, which suggests that the TLS ciphers may be too restrictive server side.

Here's the docs of potential solutions to fix this issue: https://community.cloudflare.com/t/community-tip-fixing-error-525-ssl-handshake-failed/44256

![Screenshot 2023-11-27 at 12 47 32 PM](https://github.com/zcash/protocol.z.cash/assets/23125059/ec0a635d-b9b9-4b9e-bde4-800e9bcf754e)

**Comment by str4d** [comment]
This is now fixed.
